### ISSUE TITLE
add climbing generator

### ISSUE THREAD

**Issue by vohtaski** [Sportaxy/sportaxy#144]
@primerov to add the table with data

**Comment by primerov** [comment]
Zhenya vot spisok periodov kotorie mne nado v climbing.
![image](https://user-images.githubusercontent.com/3646698/26927928-37597b4c-4c54-11e7-8a7a-dbdeecd7b239.png)

**Comment by primerov** [comment]
Competition
Relax
Anaerobic endurance
Power
Strength
Skills and aerobic endurance
Transition
Peak
